excluded:
  - DerivedData
  - Build
  - .build
  - .swiftpm
  - generate-assets-enum.swift

disabled_rules:
  - discarded_notification_center_observer
  - large_tuple
  - multiple_closures_with_trailing_closure
  - notification_center_detachment
  - orphaned_doc_comment
  - todo
  - unused_capture_list
  - trailing_newline
  - trailing_closure

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon # promote to error
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_function_chains
  - multiline_literal_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_imports
  - strict_fileprivate
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition


custom_rules:
  array_constructor:
    name: "Array/Dictionary initializer"
    regex: '[let,var] \S+ = (\[.+\]\(\))'
    capture_group: 1
    message: "Use explicit type annotation when initializing empty arrays and dictionaries"
    severity: warning

attributes:
  always_on_same_line:
    - "@IBSegueAction"
    - "@IBAction"
    - "@NSManaged"
    - "@objc"

force_cast: warning
force_try: error
function_body_length:
    warning: 60

legacy_hashing: error

identifier_name:
  allowed_symbols: "_"
  validates_start_with_lowercase: false
  excluded:
    - i
    - id
    - ui
    - c
    - d
    - e
    - v
    - x
    - y
    - z
  max_length: 120

line_length:
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true
  warning: 160
  error: 180

nesting:
    function_level:
        warning: 3
    type_level:
        warning: 3


trailing_comma:
    mandatory_comma: true
